# Backup master branch.
name: Sync master branch to backup branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Test with environment variables
        run: echo $BACKUP_NAME
        env:
          BACKUP_NAME: backup-${{ steps.date.outputs.date }}

      - uses: zent-contrib/sync-git-branch@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          BACKUP_NAME: backup-${{ steps.date.outputs.date }}
        with:
          source-branch: master
          destination-branch: $BACKUP_NAME
          destination-repo: "git@github.com:s1Sharp/cnn.git"
