# Build project
name: dotnet build

on:
  pull_request:
    paths:
      - "!.github/**"
      - ".github/workflows/build.yaml"
      - "cnn-winforms/**"

  push:
    paths:
      - "!.github/**"
      - ".github/workflows/build.yaml"
      - "cnn-winforms/**"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: windows-latest
            visual_studio: "Visual Studio 17 2022"

          - os: ubuntu-latest

    env:
      working_dir: "cnn-winforms/"
      DOTNETVERSION: "6.0"

    steps:
      - name: Setup .NET SDK ${{ env.DOTNETVERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '${{ env.DOTNETVERSION }}'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run build
        working-directory: ${{ env.working_dir }}
        run: dotnet build
