# Unit testing
name: dotnet unittest

on:
  pull_request:
    branches:    
      - 'master'
    paths:
      - "!.github/**"
      - ".github/workflows/unittest.yaml"
      - "cnn-winforms/**"

  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'master'
    paths:
      - "!.github/**"
      - ".github/workflows/unittest.yaml"
      - "cnn-winforms/**"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: windows-2022
            visual_studio: "Visual Studio 17 2022"

          - os: windows-2019
            visual_studio: "Visual Studio 17 2022"

          - os: ubuntu-latest

    env:
      working_dir: "cnn-winforms/"
      DOTNETVERSION: "6.0"

    steps:
      - name: Setup .NET SDK ${{ env.DOTNETVERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version:  '${{ env.DOTNETVERSION }}'

      - name: Checkout repo
        uses: actions/checkout@v2.1.0

      - name: Run unittest
        working-directory: ${{ env.working_dir }}
        run: dotnet test
